Szaman
ppknUWr/ppkn-discord-bot pull request #21
Opened 2020-11-13 14:56 UTC by MikolajMagaj

Zrobiłem swój task, proszę o feedback

2020-11-14 16:22 UTC, HoopDead requested changes
Cześć Mikołaj!

Generalnie kod zrobiony jest dobrze, chociaż jest kilka rzeczy, które można przepisać na "bardziej" aktualny standard. Mam tutaj na myśli, że podejście w ten sposób:

 ``` python3
        f=open(path_in_str,"r")
        print(f.read())
        f.close()
```

Jest przestarzałe i było używane bodajże w standardzie Pythona 2.x, od 3.x wszedł context manager (coś, o co często pytają na rozmowie o prace), dlatego zmieniłbym wczytywanie na

``` with open(path_in_str, "r") as f:
```
I dalej kod wygląda bardzo podobnie (https://www.pythonforbeginners.com/files/with-statement-in-python).

2020-11-14 16:57 UTC, xdexer commented
Cześć, z mojej strony, uważam, że kod jest ok.Swoich uwag nie zgłaszam, ponieważ Python nie jest moją mocną stroną. Uwagi Mateusza są jak najbardziej zasadne i warto by było je zastosować, nie tylko w ramach poznania nowoczesnych części pythona, ale też jako ćwiczenie odświeżenia kodu. Sama zmiana nie powinna długo zająć.

2020-11-14 16:58 UTC, xdexer reviewed
Cześć, z mojej strony, uważam, że kod jest ok.Swoich uwag nie zgłaszam, ponieważ Python nie jest moją mocną stroną. Uwagi Mateusza są jak najbardziej zasadne i warto by było je zastosować, nie tylko w ramach poznania nowoczesnych części pythona, ale też jako ćwiczenie odświeżenia kodu. Sama zmiana nie powinna długo zająć.

2020-11-14 19:51 UTC, HoopDead approved these changes
Z mojej strony jest wszystko okej. Postaram się jutro wydać kolejnego taska ;)

2020-11-14 20:00 UTC, xdexer approved these changes
Super robota, widać, że coraz lepiej Ci idzie :) , oby tak dalej

2020-11-15 11:54 UTC, merged

2020-11-16 19:28 UTC, Motii1 commented
@xdexer Zauważyłem, że wiele osób rzuca mnóstwo commitów o tych samych nazwach. Odnośnie tego brancha i wielu innych mimo, że został zmergowany uważam, że nie powinien być ze względu na mnogość commitów o tych samych nazwach. Proponowałbym je squashować